# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      id: example-test-runner

      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "::set-output name=sample-tests-ouput::$(npm run test-examples)\n"
    
    - name: Update failing files
      run: node test-ouput-parser.js ${{example-text-runner.outputs.sample-tests-output}}
